showNewVersionIcon: true
hideAfterStartup: false
randomControllerPort: true
runTimeFormat: "hh : mm : ss"
editor: 0
theme: 1
trayOrders:
  - - icon
  - - status
    - traffic
    - text
hideTrayIcon: false
randomMixedPort: false
connShowProcess: true
showTrayProxyDelayIndicator: true
unsafeURLsText: |
  urls: ["blj.shmh.gov.cn"]
