mixed-port: 41001
allow-lan: true
external-controller: 127.0.0.1:50319
secret: 'c7d7a172-23ca-4302-a7a5-c9aff2e4b79e'
dns:
  enable: true
  enhanced-mode: fake-ip # 或 redir-host
  listen: 127.0.0.1:53
  nameserver:
    - 223.5.5.5
experimental:
  interface-name: 以太网 # WLAN 为物理网卡名
ipv6: true
